baseurl: /homepage-testen

collections:
  products:
    output: true
    permalink: /products/:path/
  
  UnternehmenFolder:
    output: true
    permalink: /UnternehmenFolder/:path/

  defaults:
  - scope:
      path: ""
      type: "products"
    values:
      layout: "default"

  - scope:
      path: ""
      type: "UnternehmenFolder"
    values:
      layout: "default"
