baseurl: /homepage-testen

collections:
  products:
    output: true
    permalink: /products/:path/

  defaults:
  - scope:
      path: ""
      type: "products"
    values:
      layout: "default"
      